### PR TITLE
added parameter column for cli tables

### LINKED ISSUE #53: Update SDK to handle details about module arguments and types
Depends on [this](https://github.com/NapthaAI/node/issues/98) issue in napthaai/node.

Calling `naptha agents` should display the new module arguments and types.

### PR DESCRIPTION
**Pull request by miguelg719**
Orchestrators, agents, and environments should all now have a parameter column.

Fixes #53

### CODE REVIEW

**Comment by richardblythman** [comment]
@miguelg719 we should also add parameters to the dicts in create_agent() and publish_agent().

**Comment by miguelg719** [comment]
Totally, let me get to that after fixing the node issue

**Comment by miguelg719** [comment]
pushed update, unsure about the publish package parameter value can you take a look @richardblythman

**Comment by richardblythman** [comment]
> pushed update, unsure about the publish package parameter value can you take a look @richardblythman

Actually, publish isn't actively in use (it's related to decorators), so didn't test it. We can leave it as is with your changes.

**Pull request merged**
